# Generated by Django 4.2.7 on 2023-11-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='pin',
            field=models.IntegerField(),
        ),
    ]
